
server:
  port: 7070
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: info
    com.wis.libraryservice: info

spring:
  application:
    name: libraryservice

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
 
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console.settings.web-allow-others: false

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher